backend/models/Event.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "event".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $created_data
 */
class Event extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'event';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'description', 'created_data'], 'required'],
            [['created_data'], 'safe'],
            [['title', 'description'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'created_data' => 'Created Data',
        ];
    }
}

backend/controllers/EventController.php
<?php

namespace backend\controllers;
use Yii;
use app\models\event;
use app\models\eventSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\TblAppointments;

/**
 * EventController implements the CRUD actions for event model.
 */
class EventController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all event models.
     * @return mixed
     */
    public function actionIndex()
    {
       $events=TblAppointments::find()->all();
       $tasks=[];
       foreach($events as $eve)
       {

            $event = new \yii2fullcalendar\models\event();
            $event->id = $eve->id;
            $event->title = $eve->note;
            $date=date("Y-m-d H:i:s", $eve->date);
            $event->start = $date;
            $tasks[] = $event;



       }
            return $this->render('/site/event/indexevent', [
               'event'=>$tasks,
            ]);

    }

    /**
     * Displays a single event model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('/site/event/viewevent', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new event();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->renderAjax('/site/event/createevent', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/site/event/view', 'id' => $model->id]);
        }

        return $this->render('/site/event/updateevent', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['/site/event/indexevent']);
    }

    /**
     * Finds the event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = event::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Response;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use app\models\TblBrands;
use app\models\TblBrandsSearch;
use app\models\TblProducts;
use app\models\TblProductsSearch;
use app\models\TblProductType;
use yii\widgets\ActiveForm;
use app\models\TblSheen;
use app\models\TblSheenSearch;
use app\models\TblPrepLevel;
use app\models\tblPrepLevelSearch;
use app\models\TblComponentGroups;
use app\models\TblComponentGroupsSearch;
use app\models\TblRoomTypes;
use app\models\Tbl_rooms_typesSearch;
use app\models\TblColorTags;
use app\models\TblColorTagsSearch;
use app\models\TblSpecialItems;
use app\models\TblSpecialItemsSearch;
use app\models\TblStrengths;
use app\models\TblStrengthsSearch;
use app\models\TblComponents;
use app\models\TblComponentsSearch;
use app\models\TblComponentType;
use app\models\Model;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;
use app\models\TblColors;
use app\models\TblColorsSearch;
use app\models\TblTiers;
use app\models\TblTiers_Search;
use app\models\TblTierCoats;
use yii\helpers\Html;
use yii\filters\auth\QueryParamAuth;
use app\models\TblProductInventory;
use app\models\TblProductStock;
use yii\db\Command;
use yii\data\Pagination;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','brand','create','validatebrand','update','product','updateproduct','createproduct','uploadcsv','downloadcsv','sheen','createsheen','updatesheen','validateproduct','validatesheen','prep','createprep','validateprep','updateprep','createcomponent','updatecomponent','createroom','updateroom','createcolor','updatecolor','createspecial','updatespecial','createstrength','updatestrength','validateprepupdate','validatebrandupdate','validateproductupdate','validatesheenupdate','validatecomponentupdate','validatecomponent','validateroomupdate','validateroom','validatecolorupdate','validatecolor','validatespecialupdate','validatespecial','validatestrengthupdate','validatestrength','createcomponentmain','validatecomponentmain','updatecomponentmain','validateupdatecomponentmain','sortbrand','sortsheen','sortcomponent','sortroom','createcolorsmain','updatecolorsmain','validatecolorsupdatemain','validatecolorsmain','createtier','validatetier','updatetier','exportbrand','data','showproduct','deletetiercoat','addsheen','savetier','undercoatproduct','deleteundercoat','updatetierimage','deleteproductstock','deletecomponenttype','selectproduct','selectproductundercoat','deleteproducttopcoat','deletesheentopcoat','deleteproductundercoat','buypackage'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }



      public function beforeAction($action) 
    { 
        $this->enableCsrfValidation = false; 
        return parent::beforeAction($action); 
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
     public function actionBuypackage(){
      $items = [];
        return $this->render('buyPackage', [
            // 'items' => $this->items,
        ]);

    }
    public function actionIndex()

    {
            $searchModel = new TblBrandsSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $dataProvider->query->orderBy(['enabled'=>SORT_DESC,'brand_order_id'=>SORT_ASC])->all();
            $model = new TblBrands();


            $searchModelproduct = new TblProductsSearch();
            $dataproviderproduct = $searchModelproduct->search(Yii::$app->request->queryParams);
            $model2 =new TblProducts();


            $searchModelSheen = new TblSheenSearch();
            $dataProviderSheen = $searchModelSheen->search(Yii::$app->request->queryParams);
            $dataProviderSheen->query->orderBy(['sheen_order_id'=>SORT_ASC])->all();
            $model3 =new  TblSheen();


            $searchModelprep = new TblPrepLevelSearch();
            $dataProviderprep = $searchModelprep->search(Yii::$app->request->queryParams);
            $dataProviderprep->query->all();
            $model4 =new TblPrepLevel();


            $searchModelcomponent = new TblComponentGroupsSearch();
            $dataProvidercomponent = $searchModelcomponent->search(Yii::$app->request->queryParams);
            $dataProvidercomponent->query->orderBy(['enabled'=>SORT_DESC])->all();
            $model5=new TblComponentGroups();


            $searchModelrooms = new Tbl_rooms_typesSearch();
            $dataProviderrooms = $searchModelrooms->search(Yii::$app->request->queryParams);
            $dataProviderrooms->query->orderBy(['room_order_id'=>SORT_ASC])->all();
            $model6=new Tblroomtypes();


            $searchModelcolor = new TblColorTagsSearch();
            $dataProvidercolor = $searchModelcolor->search(Yii::$app->request->queryParams);
            $model7=new TblColorTags();



            $searchModelspecial = new TblSpecialItemsSearch();
            $dataProviderspecial = $searchModelspecial->search(Yii::$app->request->queryParams);
            $dataProviderspecial->query->all();
            $model8= new TblSpecialItems();


            $searchModelstrength = new TblStrengthsSearch();
            $dataProviderstrength = $searchModelstrength->search(Yii::$app->request->queryParams);
            $model9=new TblStrengths();


            $searchModelcomponents = new TblComponentsSearch();
            $dataProvidercomponents = $searchModelcomponents->search(Yii::$app->request->queryParams);
            $dataProvidercomponents->query->orderBy(['component_order_id'=>SORT_ASC])->all();
            $model10=new TblComponents();


            $searchModelcolorsmain = new TblColorsSearch();
            $dataProvidercolorsmain = $searchModelcolorsmain->search(Yii::$app->request->queryParams);
            $model11=new TblColors();


            $searchModelTier = new TblTiers_Search();
            $dataProviderTier = $searchModelTier->search(Yii::$app->request->queryParams);
            $dataProviderTier->query->orderBy(['enabled'=>SORT_DESC])->all();
            $model12=new TblTiers();
            

        return $this->render('index',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model'=>$model,

            'searchModelproduct'=>$searchModelproduct,
            'dataproviderproduct'=>$dataproviderproduct,
            'model2'=>$model2,

            'searchModelSheen'=>$searchModelSheen,
            'dataProviderSheen'=>$dataProviderSheen,
            'model3' =>$model3,

            'searchModelprep'=>$searchModelprep,
            'dataProviderprep'=>$dataProviderprep,
            'model4' =>$model4,

            'searchModelcomponent' =>$searchModelcomponent,
            'dataProvidercomponent'=>$dataProvidercomponent,
            'model5'=>$model5,

            'searchModelrooms'=>$searchModelrooms,
            'dataProviderrooms'=>$dataProviderrooms,
            'model6'=> $model6,

            'searchModelcolor'=>$searchModelcolor,
            'dataProvidercolor'=>$dataProvidercolor,
            'model7'=>$model7,

            'searchModelspecial'=>$searchModelspecial,
            'dataProviderspecial'=>$dataProviderspecial,
            'model8'=>$model8,

            'searchModelstrength'=>$searchModelstrength,
            'dataProviderstrength'=>$dataProviderstrength,
            'model9'=>$model9,

            'searchModelcomponents'=>$searchModelcomponents,
            'dataProvidercomponents'=>$dataProvidercomponents,
            'model10'=>$model10,

            'searchModelcolorsmain'=>$searchModelcolorsmain,
            'dataProvidercolorsmain'=>$dataProvidercolorsmain,
            'model11'=>$model11,

            'searchModelTier' => $searchModelTier,
            'dataProviderTier' => $dataProviderTier,
            'model12'=>$model12

        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    /*public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }*/

    public function actionLogin()
        {
               if (!\Yii::$app->user->isGuest) {
                  return $this->goHome();
               }

                   $model = new LoginForm();
                   if ($model->load(Yii::$app->request->post()) && $model->loginAdmin()) {
                            //return $this->goBack();
                            return $this->redirect(['subscriber/index']);
               } else {
                       return $this->render('login', [
                            'model' => $model,
                   ]);
               }
        }


    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {

backend/views/site/event/_formevent.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\event */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_data')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/site/event/_searchevent.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\eventSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-search">

    <?php $form = ActiveForm::begin([
        'action' => ['/site/event/index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'created_data') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/site/event/createevent.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\event */

$this->title = 'Create Event';
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('/site/event/_formevent', [
        'model' => $model,
    ]) ?>

</div>

backend/views/site/event/indexevent.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\bootstrap\Modal;
/* @var $this yii\web\View */
/* @var $searchModel app\models\eventSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Events';
$this->params['breadcrumbs'][] = $this->title;
?>
<div id="wrapper">
    <div class="header">
        <img src="demo/img/pignose-logo.png" alt=""/>
        <h1>PIGNOSE Calendar</h1>
        <a href="https://github.com/KennethanCeyer/pg-calendar" target="_blank" class="ui button black">View
            project on Github</a>
        <a href="https://github.com/KennethanCeyer/pg-calendar/wiki/Documentation" target="_blank"
           class="ui button blue">Documentation</a>
        <a href="https://github.com/KennethanCeyer/pg-calendar/archive/master.zip" target="_blank"
           class="ui button teal">Download</a>
        <h4 class="version">Latest version <strong></strong></h4>
    </div>
    <div id="basic" class="article">
        <div class="title">
            <h3><span>📅 Calendar</span></h3>
            <h4>PIGNOSE Calendar is beautiful and eidetic jQuery date picker plguin</h4>
        </div>
        <div class="calendar"></div>
        <div class="box"></div>
        <ul class="ui top pointing secondary menu">
            <a href="#" role="presentation" class="item active" data-tab="html-basic">HTML</a>
            <a href="#" role="presentation" class="item" data-tab="javascript-basic">Javascript</a>
        </ul>
        <div role="tabpanel" class="ui tab segment active" data-tab="html-basic">
            <pre><code class="language-markup">&lt;div class=&quot;calendar&quot;&gt;&lt;/div&gt;</code></pre>
        </div>
        <div role="tabpanel" class="ui tab segment" data-tab="javascript-basic">
                <pre><code class="language-js">$(function() {
    $('.calendar').pignoseCalendar();
});</code></pre>
        </div>
    </div>
</div>
<div class="event-index">
<?php Pjax::begin(['timeout' => 5000,'id'=>'eventpjax']); ?>
 <?php

       Modal::begin([
          'header'=>"",
          'id'=>'modalevent',
          'size'=>'modal-lg',
        ]);
          echo "<div id='modalEvent'></div>";
          Modal::end();
     ?>
    <h1><?= Html::encode($this->title) ?></h1>
   
    <?php //echo $this->render('/site/event/_searchevent', ['model' => $searchModel]); ?>

    <p>
       <?php 
        echo  Html::button('Create event', ['value'=>Url::to( Url::base().'/event/create'),'class'=>'btn btn-primary pull-right' ,'id'=>'modalEventButton']);?>
    </p>

    <?= \yii2fullcalendar\yii2fullcalendar::widget(array(
      'events'=> $event,
  ));?>
   
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
     $(function()
{
  //
  $('#modalEventButton').click(function(){
    $('#modalevent').modal('show')
      .find('#modalEvent')
      .load ($(this).attr('value'));
  });
});
    </script>
<?php Pjax::end();?>

backend/views/site/event/updateevent.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\event */

$this->title = 'Update Event: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="event-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('/site/event/_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/site/event/viewevent.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\event */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'description',
            'created_data',
        ],
    ]) ?>

</div>