backend/controllers/PaymentController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Response;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use app\models\TblPaymentMethod;
use app\models\TblPaymentMethodSearch;
use app\models\TblPaymentOptions;
use app\models\TblPaymentOptionsSearch;

class PaymentController extends Controller
{
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index','createpaymentmethod','updatepaymentmethod','createpaymentterm','updatepaymentterm'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }



    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }



    public function beforeAction($action) 
    { 
        $this->enableCsrfValidation = false; 
        return parent::beforeAction($action); 
    }




    public function actionLogin()
    {
           if (!\Yii::$app->user->isGuest) {
              return $this->goHome();
           }

               $model = new LoginForm();
               if ($model->load(Yii::$app->request->post()) && $model->loginAdmin()) {
                        return $this->goBack();
           } else {
                   return $this->render('login', [
                        'model' => $model,
               ]);
           }
    }


    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    public function actionIndex()
    {
    	$searchModel = new TblPaymentMethodSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new TblPaymentMethod();


        $searchModelTerm = new TblPaymentOptionsSearch();
        $dataProviderTerm = $searchModelTerm->search(Yii::$app->request->queryParams);
        $model2 = new TblPaymentOptions();

        return $this->render('/site/payment/index',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model'=>$model,

            'searchModelTerm' => $searchModelTerm,
            'dataProviderTerm' => $dataProviderTerm,
            'model2'=>$model2,
        ]);

    }


    public function actionUpdatepaymentmethod($id)
    {
         $model = TblPaymentMethod::find()->where(['id' => $id])->one();
         $default = $model->is_default;
          if ($model->load(Yii::$app->request->post()) && $model->validate()) 
          {
            // echo "<pre>";
            // print_r($_POST);
            // exit();
            if($default==$_POST['TblPaymentMethod']['is_default'])
            {
               $model->updated_at=strtotime(gmdate('y-m-d H:i:s'));
               $model->save();
               $data = 1;
               return $data;
            }
            else
            {
                $model->updated_at=strtotime(gmdate('y-m-d H:i:s'));
                if($_POST['TblPaymentMethod']['is_default']==1)
                {
                    $model2 =  TblPaymentMethod::find()->all();
                    // echo "<pre>";
                    // print_r($model2);
                    // exit();
                    foreach($model2 as $key=>$value)
                    {
                      //echo "<pre>";
                      // print_r($value->is_default);
                      // echo "<br>";
                       $value->is_default = 0;
                       $value->save(false);
                    }
                    $model->is_default = 1;
                    if($model->save())
                    {
                        $data = 1;
                        //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                        return $data;
                    }
                    else
                    {
                        $data = 0;
                        //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                        return $data;
                    }
                }
                else
                {
                  if($model->save())
                  {
                    $data = 1;
                    //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return $data;
                  }
                  else
                  {
                      $data = 0;
                      //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                      return $data;
                  }
                }
            }
              
                        
         }
        else
        {
            return $this->renderAjax('/site/payment/updatePaymentMethod', [
                'model' => $model,
            ]);
        }
    
    }

   public function actionCreatepaymentmethod()
   {
         $model = new TblPaymentMethod();;
           //

          if ($model->load(Yii::$app->request->post()) && $model->validate()) 
         {
            // echo "<pre>";
            // print_r($_POST['TblPaymentMethod']['is_default']);
          // print_r($_POST);die;
            // exit();
            $model->created_at=strtotime(gmdate('y-m-d H:i:s'));
            if (Yii::$app->user->identity->role != 20) {
              $model->company_id = $_POST['TblPaymentMethod']['company_id'];
            }
             else{
              $model->delete = 0;
            }
            if($_POST['TblPaymentMethod']['is_default']==1)
            {
                $model2 =  TblPaymentMethod::find()->all();
                // echo "<pre>";
                // print_r($model2);
                // exit();
                foreach($model2 as $key=>$value)
                {
                    $value->is_default = 0;
                    // $value->company_id = $_POST['TblPaymentMethod']['company_id'];
                    $value->save(false);
                }
                $model->is_default = 1;
                // $model->company_id = $_POST['TblPaymentMethod']['company_id'];
                if($model->save())
                {
                    $data = 1;
                    //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return $data;
                }
                else
                {
                    $data = 0;
                    //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return $data;
                }
            }
            else
            {
                if($model->save())
                {
                    $data = 1;
                    //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return $data;
                }
                else
                {
                    $data = 0;
                    //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return $data;
                }
            }
            
            
        }
        else
        {
            return $this->renderAjax('/site/payment/createPaymentMethod', [
                'model' => $model,
            ]);
        }
    
    }

    public function actionCreatepaymentterm()
    {
        $model = new TblPaymentOptions();;
           
        if ($model->load(Yii::$app->request->post()) && $model->validate()) 
         {
           $model->created_at=strtotime(gmdate('y-m-d H:i:s'));
           if (Yii::$app->user->identity->role != 20) {
              $model->company_id = $_POST['TblPaymentOptions']['company_id'];
            }
            else{
              $model->delete = 0;
            }
           if($_POST['TblPaymentOptions']['is_default']==1)
            {
                $model2 =  TblPaymentOptions::find()->all();
                // echo "<pre>";
                // print_r($model2);
                // exit();
                foreach($model2 as $key=>$value)
                {
                    $value->is_default = 0;
                    $value->save(false);
                }
                $model->is_default = 1;
                if($model->save())
                {
                    $data = 1;
                    //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return $data;
                }
                else
                {
                    $data = 0;
                    //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return $data;
                }
            }
            else
            {
              if($model->save())
                {
                    $data = 1;
                    //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return $data;
                }
                else
                {
                    $data = 0;
                    //Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return $data;
                }
            }

         }
        else
        {
            return $this->renderAjax('/site/payment/createPaymentOption', [
                'model' => $model,
            ]);
        }

    }

    public function actionUpdatepaymentterm($id)
    {
        $model = TblPaymentOptions::find()->where(['id' => $id])->one();   
        $default = $model->is_default;

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

use common\models\User;
use  yii\web\Session;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    /*public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }*/


    public function behaviors()
    {
       return [
           'access' => [
               'class' => AccessControl::className(),
               'only' => ['logout', 'signup', 'about', 'dashboard'],
               'rules' => [
                   [
                       'actions' => ['signup'],
                       'allow' => true,
                       'roles' => ['?'],
                   ],
                   [
                       'actions' => ['logout', 'dashboard'],
                       'allow' => true,
                       'roles' => ['@'],
                   ],
                   [
                       'actions' => ['about'],
                       'allow' => true,
                       'roles' => ['@'],
                       'matchCallback' => function ($rule, $action) {
                           return User::isUserAdmin(Yii::$app->user->identity->username);
                       }
                   ],
               ],
           ],
           'verbs' => [
               'class' => VerbFilter::className(),
               'actions' => [
                   'logout' => ['post'],
               ],
           ],
       ];
    }



    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {

        $this->layout = 'main_login';

        /*check if user close the browser*/

        $session = Yii::$app->session;
        // check if a session is already open
        if ($session->isActive){

                $session->close();
                Yii::$app->user->logout();               
        }

        /*check if user close the browser*/

        
        if (!Yii::$app->user->isGuest) {            
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {            
            //return $this->goBack();
            return $this->redirect(['site/dashboard']);
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        $this->layout = 'main_sidebar';
        
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionDashboard()
    {
        return $this->render('dashboard');
       
    } //actionLoader

}

backend/views/site/payment/createPaymentMethod.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\TblBrands */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tbl-payment-form">
 <?php $form = ActiveForm::begin(['id' => 'myid1']); ?>
	 <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
   <?= $form->field($model,'company_id')->textInput(['type'=>"hidden", 'value' => Yii::$app->user->identity->company_id])->label(false) ?>
    <?php $model->is_default = '0';?>
      <?= $form->field($model, 'is_default')->radioList(array('1'=>'YES','0'=>'NO')); ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success','id'=>'closepayment']) ?>
    </div>
 <?php ActiveForm::end(); ?>
</div>
<script>
$('body').on('beforeSubmit', '#myid1', function (e) {
     var pathname = window.location.href;
     //console.log(pathname);
     var form = $(this);
     //console.log("sdadas");
     // submit form
     $.ajax({
          url: form.attr('action'),
          type: 'post',
          data: form.serialize(),
          success: function (response) {
               // do something with response

                          

               if(response == 1){
                  $("#modelPaymentMethodCreate").modal('hide')
                  $('.modal-backdrop').remove();
                  // $.pjax.reload('#Paymentpjax' , {timeout : false});
                  $.pjax.reload('.printable' , {timeout : false});
                
      
               }
          },
          
     });
     e.stopImmediatePropagation();
     return false;
});





</script>

backend/views/site/payment/createPaymentOption.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\TblBrands */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tbl-payment-form">
 <?php $form = ActiveForm::begin(['id' => 'myid3']); ?>
	 <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
   <?= $form->field($model,'company_id')->textInput(['type'=>"hidden", 'value' => Yii::$app->user->identity->company_id])->label(false) ?>
   <?= $form->field($model, 'no_of_days')->textInput(['maxlength' => true]) ?>
   <?= $form->field($model, 'discount_days')->textInput(['maxlength' => true]) ?>
   <?= $form->field($model, 'discount', [
            'template' => '<strong>Discount %</strong><div class="input-group">{input}
            <span class="input-group-addon">%</span></div>{error}{hint}'
        ])->textInput(['maxlength' => true]) ?>
   <?php $model->is_default = '0';?>
   <?= $form->field($model, 'is_default')->radioList(array('1'=>'YES','0'=>'NO')); ?>
   <?= $form->field($model, 'description')->textarea(['rows' => '6']) ?>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>
 <?php ActiveForm::end(); ?>
</div>
<script>
$('body').on('beforeSubmit', '#myid3', function (e) {
     var pathname = window.location.href;
     //console.log(pathname);
     var form = $(this);
     //console.log("sdadas");
     // submit form
     $.ajax({
          url: form.attr('action'),
          type: 'post',
          data: form.serialize(),
          success: function (response) {
               // do something with response

                          

               if(response == 1){
                  $("#modelTermOptions").modal('hide')
                  $('.modal-backdrop').remove();
                  // $.pjax.reload('#PaymentTermPjax' , {timeout : false});
                  $.pjax.reload('.printable' , {timeout : false});
                
      
               }
          },
          
     });
     e.stopImmediatePropagation();
     return false;
});





</script>

backend/views/site/payment/paymentindex.php
<?php

use yii\helpers\Html;
//use yii\grid\GridView;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\widgets\Pjax;
use dosamigos\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TblSpecialItemsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


?>
<div class="tbl-special-items-index">

    <h1><?= Html::encode($this->title) ?></h1>
  
<?php Pjax::begin(['timeout' => 5000,'id'=>'Paymentpjax']);?>
<?php  echo  Html::button('<img src="'.Url::base().'/uploads/add.png"width="17" height="17"/>', ['value'=>Url::to( Url::base().'/payment/createpaymentmethod'),'class'=>'btn btn-primary pull-right' ,'id'=>'modalPaymentMethodCreate']);?>
    
 <?php

Modal::begin([
    'header'=>'',
    'id'=>'modelPaymentMethodCreate',
    'size'=>'modal-lg',
]);
  echo "<div id='modalMethodPayment'><div style='text-align:center'><img src='".Url::base()."/uploads/avatar2.gif' height='100' width='100'></div></div>";

Modal::end();
?>
   
  <?php  //echo $this->render('_searchspecial', ['model' => $searchModelspecial]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'rowOptions'   => function ($model, $key, $index, $grid) {
          if ($model->delete != 0 || Yii::$app->user->identity->role == 20 ) {
            return  [
                         "class"=>"modalButtonspecial2",'value'=>Url::base().'/payment/updatepaymentmethod?id='.$model->id
                    ];
          }
          else{
             return  [
                        "class"=>"modalButtonspecials2"
                    ];
          }
              
              },
        'behaviors' => [
            [
                'class' => '\dosamigos\grid\behaviors\LoadingBehavior',
                'type' => 'spinner'
            ]
        ],
        'columns' => [
           
            //'name',
            ['attribute'=>'Name','value' =>'name','filter' =>false],
            ['attribute'=>'Default',
             'value' =>
                       function($model){
                         if($model->is_default == '1'){
                            return 'Default';
                         }
                         else
                         {
                            return '';
                         }
                       },



             'filter' =>false,],

            ['class' => 'yii\grid\ActionColumn',
               'header' => 'UPDATE',
               'headerOptions' => ['style' => 'color:#337ab7'],
               'template' => '{update}',
               'buttons' => [
                    'update' => function ($url, $model,$id) {
                      if ($model->delete != 0 || Yii::$app->user->identity->role == 20 ) {
                        return Html::a('<span class=""><img src="'.Url::base().'/uploads/update.png" width="13" height="13"/></span>', $url, [
                                 "class"=>"modalButtonspecial2",'value'=>Url::base().'/payment/updatepaymentmethod?id='.$model->id
                                  ]);
                      }
                      else{
                        return '-';
                      }
                                  
                                },
                    ],
              'urlCreator' => function ($action, $model, $key, $index) {
               Url::to(['updatepaymentmethod?id='.$model->id],['id'=>'modal'])   ;         
                //$url ='update?id='.$model->brand_id;
              //return $url;
                 
                 //return Html::a($url, ['title' => 'view'            

          },      
           ],
         ],
      ]); ?>
</div>
<script>
  $('#modalPaymentMethodCreate').click(function(){
     $('#modelPaymentMethodCreate').modal('show')
      .find('#modalMethodPayment') .load ($(this).attr('value'))
      $('.modal-header').html('<h5>Create Payment Method</h5><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>');

  })

  $('.modalButtonspecial2').click(function(){
     $('#modelPaymentMethodCreate').modal('show')
      .find('#modalMethodPayment') .load ($(this).attr('value'))
      $('.modal-header').html('<h5>Edit Payment Method</h5><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>');

  })
  
</script>
<?php Pjax::end();?>

backend/views/site/payment/paymentterm.php
<?php

use yii\helpers\Html;
//use yii\grid\GridView;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\widgets\Pjax;
use dosamigos\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TblSpecialItemsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


?>
<div class="tbl-special-items-index">

    <h1><?= Html::encode($this->title) ?></h1>
  
<?php Pjax::begin(['timeout' => 5000,'id'=>'PaymentTermPjax']);?>
<?php  echo  Html::button('<img src="'.Url::base().'/uploads/add.png"width="17" height="17"/>', ['value'=>Url::to( Url::base().'/payment/createpaymentterm'),'class'=>'btn btn-primary pull-right' ,'id'=>'modalTerm']);?>
    
 <?php

Modal::begin([
    'header'=>'',
    'id'=>'modelTermOptions',
    'size'=>'modal-lg',
]);
echo "<div id='modalPaymentOptions'><div style='text-align:center'><img src='".Url::base()."/uploads/avatar2.gif' height='100' width='100'></div></div>";

Modal::end();
?>
   
  <?php  //echo $this->render('_searchspecial', ['model' => $searchModelspecial]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProviderTerm,
        //'filterModel' => $searchModel,
        'rowOptions'   => function ($model2, $key, $index, $grid) {
          if ($model2->delete != 0 || Yii::$app->user->identity->role == 20 ) {
            return  [
                           "class"=>"modalButtonUpdate",'value'=>Url::base().'/payment/updatepaymentterm?id='.$model2->id
                      ];
          }
            else{
              return  [
                           "class"=>"modalButtonUpdatexe"
                      ];
            }
              
              },
        'behaviors' => [
            [
                'class' => '\dosamigos\grid\behaviors\LoadingBehavior',
                'type' => 'spinner'
            ]
        ],
        'columns' => [
           
            //'name',
            ['attribute'=>'Name','value' =>'name','filter' =>false],
            ['attribute'=>'Description','value' =>'description','filter' =>false],
            ['attribute'=>'Number Of Days','value' =>'no_of_days','filter' =>false],
            ['attribute'=>'Discount %','value' =>'discount','filter' =>false],
            ['attribute'=>'Discount Days','value' =>'discount_days','filter' =>false],
            ['attribute'=>'Default',
             'value' =>
                       function($model2){
                         if($model2->is_default == '1'){
                            return 'Default';
                         }
                         else
                         {
                            return '';
                         }
                       },



             'filter' =>false,],
             // ['attribute'=>'Enabled',
             // 'value' =>
             //           function($model2){
             //             if($model2->enabled == '1'){
             //                return 'Enabled';
             //             }
             //             else
             //             {
             //                return '';
             //             }
             //           },



             // 'filter' =>false,],

            ['class' => 'yii\grid\ActionColumn',
               'header' => 'UPDATE',
               'headerOptions' => ['style' => 'color:#337ab7'],
               'template' => '{update}',
               'buttons' => [
                    'update' => function ($url, $model2 ,$id) {
                      if ($model2->delete != 0 || Yii::$app->user->identity->role == 20 ) {
                        return Html::a('<span class=""><img src="'.Url::base().'/uploads/update.png" width="13" height="13"/></span>', $url, [
                                 "class"=>"modalButtonUpdate",'value'=>Url::base().'/payment/updatepaymentmethod?id='.$model2->id
                                  ]);
                      }
                      else{
                        return '-';
                      }
                                  
                                },
                    ],
              'urlCreator' => function ($action, $model2, $key, $index) {
               Url::to(['update?id='.$model2->id],['id'=>'modal'])   ;         
                //$url ='update?id='.$model->brand_id;
              //return $url;
                 
                 //return Html::a($url, ['title' => 'view'            

          		},      
           ],
        ],
    ]); ?>
</div>
<script>

$('#modalTerm').click(function(){
  $('#modelTermOptions').modal('show')
  .find('#modalPaymentOptions') .load ($(this).attr('value'))
  $('.modal-header').html('<h5>Create Payment Term</h5><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>')
})

$('.modalButtonUpdate').click(function(){
	 $('#modelTermOptions').modal('show')
	 .find('#modalPaymentOptions') .load ($(this).attr('value'))
	 $('.modal-header').html('<h5>Edit Payment Term</h5><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>')
})
</script>
<?php Pjax::end();?>

backend/views/site/payment/updatePaymentMethod.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\TblBrands */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tbl-payment-form">
 <?php $form = ActiveForm::begin(['id' => 'myid2']); ?>
	 <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'is_default')->radioList(array('1'=>'YES','0'=>'NO')); ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success','id'=>'closepayment']) ?>
    </div>
 <?php ActiveForm::end(); ?>
</div>
<script>
$('body').on('beforeSubmit', '#myid2', function (e) {
     var pathname = window.location.href;
     //console.log(pathname);
     var form = $(this);
     //console.log("sdadas");
     // submit form
     $.ajax({
          url: form.attr('action'),
          type: 'post',
          data: form.serialize(),
          success: function (response) {
               // do something with response

                          

               if(response == 1){
                  $("#modelPaymentMethodCreate").modal('hide')
                  $('.modal-backdrop').remove();
                  $.pjax.reload('#Paymentpjax' , {timeout : false});
                
      
               }
          },
          
     });
     e.stopImmediatePropagation();
     return false;
});





</script>